"""Stage 3: the agent tier.

Composes S1 and S2, then resolves what neither could settle.

  compose   S1 defers an item -> S2 supplies a ranked shortlist -> this stage decides.
  pass 1    Batch API, one structured call per item, choose from the shortlist or abstain.
            Cheap, parallel, handles the bulk.
  pass 2    The residual from pass 1 (abstained or unsure) gets an agent loop with tools.
            Small volume, so a real multi-turn loop is affordable here and nowhere else.

The reason pass 2 exists, and the reason it has tools:

    Every stage below this one is trapped inside the retriever's top-K. If the correct
    leaf was never retrieved -- 2.3% of items at K=50 -- no reranker, threshold or
    prediction set can recover it. An agent that can SEARCH THE TAXONOMY can. That is
    the only component in the whole cascade able to break the retrieval ceiling, which
    is what earns it a tier of its own.

Two prompt decisions that are load-bearing, both testable with --ablate:

  ORDER   candidates are shuffled and carry no retrieval scores. Presented in rank order
          an LLM anchors on position 1, so its answers correlate with the retriever and
          you have built an expensive way to agree with the bi-encoder.
  ABSTAIN none_of_these needs explicit permission, a criterion, AND a worked example.
          Without the example models almost never abstain, and every retrieval miss then
          becomes a confident wrong label in the training corpus.
"""
import argparse
import json
import os
import random
import re
import time
from pathlib import Path

import numpy as np
import pandas as pd

from shortlist import MODES, build_shortlist

MODEL = "claude-sonnet-4-5"
NONE = "NONE_OF_THESE"
STRATA = ["head", "torso", "tail", "few_shot", "zero_shot"]
SEED = 17

RECORD_TOOL = {
    "name": "record_category",
    "description": "Record the single category the product belongs to, or abstain.",
    "input_schema": {
        "type": "object",
        "properties": {
            "leaf_id": {
                "type": "string",
                "description": f"Exactly one category id from the list, or '{NONE}' if none fit.",
            },
            "confidence": {
                "type": "string",
                "enum": ["certain", "probable", "unsure"],
                "description": "Categorical, not a number: self-reported numeric confidence "
                               "piles up at 0.9 and carries little information.",
            },
        },
        "required": ["leaf_id", "confidence"],
    },
}

SYSTEM_HEAD = """You assign e-commerce products to exactly one catalogue category.

You will see a product listing and a list of candidate categories. The candidates are in
no meaningful order."""

# The prompt must describe what is actually in the candidate block. v2_path carries a name
# and a hierarchy path and nothing else; promising a description the model cannot find is
# a defect, not a harmless flourish.
SYSTEM_DOCS = {
    "v1_name": "Each candidate shows only an id and a name.",
    "v2_path": "Each candidate shows an id, a name, and its position in the catalogue "
               "hierarchy. Treat the path as indicative, not definitive: for broad "
               "catch-all categories it shows only the most common sub-branch, so a path "
               "that looks narrow may still belong to a wide category.",
    "v3_proto": "Each candidate shows an id, a name, its position in the catalogue "
                "hierarchy, and example products already filed under it.",
    "v4_desc": "Each candidate shows an id, a name, its position in the catalogue "
               "hierarchy, example products filed under it, and a description of what "
               "belongs there.",
}

SYSTEM_RULES = f"""
Rules:
- Choose the category describing what the product IS, not what it mentions. A phone case
  with a card slot is a phone case, not a wallet.
- If no candidate fits the product, answer '{NONE}'. This is a correct and useful answer:
  the candidate list is generated by a retrieval system that sometimes misses. Abstaining
  flags that, whereas a forced guess silently corrupts the training data.
- Use 'unsure' freely. A flagged uncertainty is cheap; a confident error is not.

Always answer by calling record_category."""


def system_prompt(variant: str) -> str:
    return f"{SYSTEM_HEAD}\n{SYSTEM_DOCS[variant]}\n{SYSTEM_RULES}"

FEWSHOT_USER = """PRODUCT
Title: Amazon Brand - Solimo Leather Flip Cover Wallet Case for Samsung Galaxy S10
Brand: Amazon Brand - Solimo

CANDIDATE CATEGORIES
[WALLET] Bags & Accessories > Wallets. Folding cases for carrying cash and cards.
[CELLULAR_PHONE_CASE] Electronics > Mobile > Protection. Covers that protect a phone body.
[LUGGAGE] Travel > Luggage. Suitcases and travel bags."""

FEWSHOT_ASSISTANT_ARGS = {"leaf_id": "CELLULAR_PHONE_CASE", "confidence": "certain"}

FEWSHOT_USER_ABSTAIN = """PRODUCT
Title: Replacement Carbon Filter Cartridge for Countertop Water Purifier, 2-Pack
Brand: AquaPure

CANDIDATE CATEGORIES
[CHAIR] Furniture > Seating. Chairs and stools.
[SHOES] Apparel > Footwear. Shoes and sandals.
[GROCERY] Food > Pantry. Packaged food and drink."""

FEWSHOT_ASSISTANT_ABSTAIN_ARGS = {"leaf_id": NONE, "confidence": "certain"}


def render_item(row) -> str:
    parts = [f"Title: {row.title}"]
    if row.brand:
        parts.append(f"Brand: {row.brand}")
    if row.bullets:
        parts.append(f"Details: {row.bullets[:400]}")
    return "PRODUCT\n" + "\n".join(parts)


def clean(s: str) -> str:
    """Generated descriptions come back with markdown headers and hard wraps. Neither
    survives usefully inside a prompt line; both cost tokens."""
    return re.sub(r"\s+", " ", re.sub(r"[#*`]+", " ", s)).strip()


def compose_doc(entry: dict, variant: str, limit: int) -> str:
    """v4_desc is assembled as '<v3_proto> <description>', so the description sits LAST
    and a naive truncation deletes it first — exactly the part that says what belongs in
    a category, and the part that cost money. Put the description straight after the path
    and let the example titles absorb the cut instead.

    The split is exact rather than parsed: v3_proto is a literal prefix of v4_desc, and
    v2_path is a literal prefix of v3_proto, so slicing by length recovers each piece.
    """
    if variant != "v4_desc":
        return clean(entry[variant])[:limit]
    base, proto, full = entry["v2_path"], entry["v3_proto"], entry["v4_desc"]
    desc = clean(full[len(proto):])
    examples = clean(proto[len(base):])
    out = f"{clean(base)} {desc}"[:limit]
    room = limit - len(out)
    return out + (f" {examples[:room]}" if room > 40 else "")


def render_candidates(ids, docs, leaves, rng, shuffle: bool) -> str:
    ids = list(ids)
    if shuffle:
        rng.shuffle(ids)
    lines = [f"[{leaves[i]}] {docs[i]}" for i in ids]
    return "CANDIDATE CATEGORIES\n" + "\n".join(lines)


def build_messages(item_text: str, cand_text: str, fewshot: bool) -> list:
    msgs = []
    if fewshot:
        msgs += [
            {"role": "user", "content": FEWSHOT_USER},
            {"role": "assistant", "content": [
                {"type": "tool_use", "id": "t1", "name": "record_category",
                 "input": FEWSHOT_ASSISTANT_ARGS}]},
            {"role": "user", "content": [
                {"type": "tool_result", "tool_use_id": "t1", "content": "recorded"}]},
            {"role": "user", "content": FEWSHOT_USER_ABSTAIN},
            {"role": "assistant", "content": [
                {"type": "tool_use", "id": "t2", "name": "record_category",
                 "input": FEWSHOT_ASSISTANT_ABSTAIN_ARGS}]},
            {"role": "user", "content": [
                {"type": "tool_result", "tool_use_id": "t2", "content": "recorded"}]},
        ]
    msgs.append({"role": "user", "content": f"{item_text}\n\n{cand_text}"})
    return msgs


def compose(data: Path, s1_tag: str, s2_tag: str, tau: float):
    """Rebuild both scripts' evaluation slices deterministically and intersect them.

    Neither script saves item ids, so alignment is by reconstruction. The assertions
    below are the whole safety net: a silent misalignment here would attribute every
    S1 probability to the wrong item and nothing downstream would look wrong.
    """
    df = pd.read_parquet(data / "items.parquet")
    s1_ev = df[df.split.isin(["val", "test"])].reset_index(drop=True)
    probs = np.load(data / "stage1" / f"probs_{s1_tag}.npy")
    classes = json.loads((data / "stage1" / f"classes_{s1_tag}.json").read_text())
    assert len(s1_ev) == len(probs), f"S1 slice {len(s1_ev)} != probs {len(probs)}"

    scores = np.load(data / "stage2" / f"scores_test_{s2_tag}.npy")
    cands = np.load(data / "stage2" / "cands_test.npy")
    s2_ev = df[df.split == "test"].reset_index(drop=True)
    if len(s2_ev) != len(scores):                       # stage2 ran with --limit-eval
        s2_ev = s2_ev.sample(len(scores), random_state=SEED).reset_index(drop=True)
    assert len(s2_ev) == len(scores) == len(cands), "S2 slice does not match its arrays"

    s1_pos = {iid: i for i, iid in enumerate(s1_ev.item_id)}
    keep = [(j, s1_pos[iid]) for j, iid in enumerate(s2_ev.item_id) if iid in s1_pos]
    assert keep, "no overlap between the S1 and S2 slices"
    j2, i1 = np.array([k[0] for k in keep]), np.array([k[1] for k in keep])

    other = classes.index("__OTHER__") if "__OTHER__" in classes else -1
    p = probs[i1]
    deferred = (p.argmax(1) == other) | (p.max(1) < tau)
    ev = s2_ev.iloc[j2].reset_index(drop=True)
    print(f"Composed {len(ev):,} items present in both slices")
    print(f"S1 defers {deferred.mean():.1%} at tau={tau} -> {int(deferred.sum()):,} reach Stage 3")
    return ev, deferred, cands[j2], scores[j2]


def call_batch(client, reqs, poll=30):
    batch = client.messages.batches.create(requests=reqs)
    print(f"batch {batch.id}: {len(reqs)} requests submitted", flush=True)
    while True:
        b = client.messages.batches.retrieve(batch.id)
        if b.processing_status == "ended":
            break
        print(f"  {b.processing_status} …", flush=True)
        time.sleep(poll)
    out = {}
    for r in client.messages.batches.results(batch.id):
        if r.result.type != "succeeded":
            out[r.custom_id] = None
            continue
        blocks = [c for c in r.result.message.content if c.type == "tool_use"]
        out[r.custom_id] = blocks[0].input if blocks else None
    return out


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--data", type=Path, default=Path("data"))
    ap.add_argument("--s1-tag", default="head69")
    ap.add_argument("--s2-tag", default="ft2")
    ap.add_argument("--tau", type=float, default=0.900,
                    help="S1's operating point — fitted on val at 98%% precision")
    ap.add_argument("--shortlist", type=int, default=10, help="candidates shown to the model")
    ap.add_argument("--shortlist-mode", choices=list(MODES), default="fused",
                    help="which Stage 2 ordering the agent reads. Must match what "
                         "pipeline.py builds, or the agent is scored on a list the "
                         "cascade would never hand it. See shortlist.py for the table.")
    ap.add_argument("--limit", type=int, default=0, help="cap escalated items (cost control)")
    ap.add_argument("--doc-variant", default="v2_path",
                    choices=["v1_name", "v2_path", "v3_proto", "v4_desc"])
    ap.add_argument("--doc-chars", type=int, default=420,
                    help="per-candidate budget. 10 candidates x 420 chars is ~1.2k tokens "
                         "of the prompt; raise it and the shortlist starts to dominate cost.")
    ap.add_argument("--ablate", choices=["none", "rank-order", "no-fewshot"], default="none",
                    help="rank-order: present candidates by retrieval rank (tests anchoring). "
                         "no-fewshot: drop the worked examples (tests whether abstention fires).")
    ap.add_argument("--dry-run", action="store_true", help="build and print one prompt, spend nothing")
    args = ap.parse_args()

    rng = random.Random(SEED)
    sys_prompt = system_prompt(args.doc_variant)
    docs_all = json.loads((args.data / "label_docs.json").read_text())
    leaves = json.loads((args.data / "stage2" / "leaves.json").read_text())
    docs = [compose_doc(docs_all[l], args.doc_variant, args.doc_chars) for l in leaves]

    ev, deferred, cands, scores = compose(args.data, args.s1_tag, args.s2_tag, args.tau)
    idx = np.where(deferred)[0]
    if args.limit:
        idx = idx[: args.limit]
        print(f"Capped to {len(idx):,} escalated items")

    shortlists = build_shortlist(cands, scores, args.shortlist, args.shortlist_mode)
    print(f"Shortlist: {args.shortlist} candidates, '{args.shortlist_mode}' ordering")

    reqs = []
    for i in idx:
        item = render_item(ev.iloc[i])
        cand = render_candidates(shortlists[i], docs, leaves, rng,
                                 shuffle=args.ablate != "rank-order")
        reqs.append({
            "custom_id": str(ev.item_id.iloc[i]),
            "params": {
                "model": MODEL, "max_tokens": 200, "system": sys_prompt,
                "messages": build_messages(item, cand, fewshot=args.ablate != "no-fewshot"),
                "tools": [RECORD_TOOL],
                "tool_choice": {"type": "tool", "name": "record_category"},
            },
        })

    if args.dry_run or not reqs:
        print("\n--- example prompt ---\n" + sys_prompt + "\n")
        if reqs:
            print(reqs[0]["params"]["messages"][-1]["content"])
        print(f"\n{len(reqs):,} requests would be sent. Nothing spent.")
        return
    if not os.environ.get("ANTHROPIC_API_KEY"):
        raise SystemExit("ANTHROPIC_API_KEY is not set.")

    from anthropic import Anthropic
    res = call_batch(Anthropic(), reqs)

    gold = ev.product_type.to_numpy()
    rows = []
    for i in idx:
        iid = str(ev.item_id.iloc[i])
        r = res.get(iid) or {}
        rows.append({
            "item_id": iid, "stratum": ev.stratum.iloc[i], "gold": gold[i],
            "pred": r.get("leaf_id"), "confidence": r.get("confidence"),
            # top of the ordering the agent actually saw — the no-agent baseline it
            # has to beat. Under 'fused' that is the retriever's top-1, not the CE's.
            "s2_top1": leaves[shortlists[i][0]],
            "gold_in_shortlist": gold[i] in [leaves[c] for c in shortlists[i]],
            # Recorded so a later run cannot be compared against a different ordering
            # without it being visible in the file.
            "shortlist_mode": args.shortlist_mode, "tau": args.tau,
        })
    out = pd.DataFrame(rows)
    out.to_csv(args.data / "stage3_results.csv", index=False)

    out["correct"] = out.pred == out.gold
    out["s2_correct"] = out.s2_top1 == out.gold
    out["abstained"] = out.pred == NONE
    print(f"\n=== Stage 3 on {len(out):,} escalated items ===")
    print(f"{'stratum':>10s} {'n':>5s} {'agent':>7s} {'S2 top1':>8s} {'lift':>7s} "
          f"{'abstain':>8s} {'gold in list':>13s}")
    for st in STRATA + ["ALL"]:
        s = out if st == "ALL" else out[out.stratum == st]
        if s.empty:
            continue
        a = s.groupby("gold").correct.mean().mean()
        b = s.groupby("gold").s2_correct.mean().mean()
        print(f"{st:>10s} {len(s):>5d} {a:>7.3f} {b:>8.3f} {a-b:>+7.3f} "
              f"{s.abstained.mean():>8.3f} {s.gold_in_shortlist.mean():>13.3f}")

    miss = out[~out.gold_in_shortlist]
    if len(miss):
        print(f"\nRetrieval missed the gold leaf for {len(miss)} items. The agent abstained on "
              f"{miss.abstained.mean():.1%} of them.")
        print("That rate is the honest measure of the abstention prompt: those items are")
        print("unanswerable from the shortlist, so anything but an abstention is a wrong label.")
    print(f"\nWrote {args.data / 'stage3_results.csv'}")
    print("Failures parsed as None:", int(out.pred.isna().sum()))


if __name__ == "__main__":
    main()
